# Generated by Django 5.2.4 on 2025-07-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoexcluidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('apellido_pat', models.CharField(max_length=100, null=True)),
                ('apellido_mat', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('telefono_movil', models.CharField(max_length=100, null=True)),
                ('ap_inscrito', models.CharField(max_length=100, null=True)),
                ('ap_aceptado', models.CharField(max_length=100, null=True)),
                ('nombre_ap', models.CharField(max_length=200, null=True)),
                ('apellido_pat_ap', models.CharField(max_length=100, null=True)),
                ('apellido_mat_ap', models.CharField(max_length=100, null=True)),
                ('email_ap', models.CharField(max_length=100, null=True)),
                ('telefono_ap', models.CharField(max_length=100, null=True)),
                ('telefono_movil_ap', models.CharField(max_length=100, null=True)),
                ('activo', models.CharField(max_length=100, null=True)),
                ('fecha_ae', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sospechosos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
